DROP TABLE IF EXISTS book;

CREATE TABLE book (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PUBLICATION_STATUS  VARCHAR(250) NOT NULL,
  PUBLICATION_DATE DATE 
);

INSERT INTO book (PUBLICATION_STATUS) VALUES
  ('ACTIVE')
  ;